accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('',views.signup,name='signup'),
    path('profile',views.profile,name='profile'),
    path(
        'profile/edit',
        views.profile_edit,name='profileEdit'
    ),
    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='registration/login.html'
        ),
        name='login'
    ),
    path(
        'loggedOut/',
        auth_views.LoginView.as_view(
            template_name='registration/logged_out.html'
            ),
        name='loggedOut'
    ),
    path('password_change_form/',auth_views.LoginView.as_view(template_name='registration/password_change_form.html'),name='password_change_form'),
    path('password_reset_complete/',auth_views.LoginView.as_view(template_name='registration/password_reset_complete.html'),name='password_reset_complete'),
    path('password_reset_confirm/',auth_views.LoginView.as_view(template_name='registration/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password_reset_done/',auth_views.LoginView.as_view(template_name='registration/password_reset_done.html'),name='password_reset_done'),
    path('password_reset_email/',auth_views.LoginView.as_view(template_name='registration/password_reset_email.html'),name='password_reset_email'),
    path(
        'password_reset_form/',
        auth_views.LoginView.as_view(template_name='registration/password_reset_form.html'),name='password_reset_form'),
]

home/urls.py
'''
from django.urls import path
from .views import home

urlpatterns = [
    path('',home,name='home'),
]
'''

from django.urls import path
from . import views

urlpatterns = [
    path('home', views.home, name="home"),
    path('edit/<int:id>/', views.edit_product, name="edit"),
    path('delete/<int:id>/', views.delete_product, name="delete"),
]

pro/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path(
        'accounts/',
        include('django.contrib.auth.urls')
        ),
    path(
        '' ,
        include('accounts.urls',namespace='accounts')
        ),
    path('admin/', admin.site.urls),
    path('home/',include('home.urls')),
]
urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT
)
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT
)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE
    )
    phone_number = models.CharField(
        max_length=15,null=True,blank=True
    )
    address = models.CharField(
       max_length=50,null=True,blank=True
    )

    def __str__(self):
        return str(self.user)

@receiver(post_save, sender=User)
def create_user_profile(
    sender,instance,created,**kwargs
):
    if created:
        Profile.objects.create(user = instance)

home/models.py
from django.contrib.auth.models import User
from django.db import models

class Product(models.Model):
    title = models.CharField(max_length=200)
    price = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # الناشر

    def __str__(self):
        return self.title

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from django.contrib.auth.models import User




class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username','email','password1','password2'
        ]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'username','email','first_name','last_name'
        ]

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['phone_number','address']

home/forms.py
from django.forms import ModelForm
from .models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['title','price']

accounts/views.py
from django.shortcuts import render,redirect
from .forms import SignupForm, UserForm, ProfileForm
from django.contrib.auth import authenticate, login
from .models import Profile
# Create your views here.

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        #if user_form.is_valid() and profile_form.is_valid():
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(
                username=username,password=password)
            login(request,user)
            return redirect('/home/home')
    else:
        form = SignupForm()
    return render(
        request,'registration/signup.html',{
            'form':form
        }
    )



def profile(request):
    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile= None
    return render(
        request,'registration/profile.html',{
            'profile':profile
        }
    )


def profile_edit(request):
    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = None
    if request.method == 'POST':
        user_form = UserForm(
            request.POST,instance=request.user
        )
        profile_form = ProfileForm(
            request.POST,instance=profile
        )
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            myForm = profile_form.save(commit=False)
            myForm.user = request.user
            myForm.save()
            return redirect('/accounts/profile')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)
    return render(
        request,'registration/profile_edit.html',{
        'user_form':user_form,
        'profile_form':profile_form
        }
    )

home/views.py
'''
from django.shortcuts import render, redirect
from .models import Product
from .forms import ProductForm
# Create your views here.

def home(request):
    pro = Product.objects.all()
    if request.method == 'POST':
        proForm = ProductForm(request.POST)
        if proForm.is_valid():
            proForm.save()
            return redirect('/')
    else :
        proForm = ProductForm()
    return render(request,'home/home.html',{
    'pro':pro,'proForm':proForm
    })
'''
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product
from .forms import ProductForm
from django.http import HttpResponseForbidden

def home(request):
    # --- البحث ---
    query = request.GET.get("q")  # اسم أو سعر
    if query:
        pro = Product.objects.filter(title__icontains=query) | Product.objects.filter(price__icontains=query)
    else:
        pro = Product.objects.all()

    # --- الإضافة ---
    if request.method == 'POST':
        proForm = ProductForm(request.POST)
            #if user_form.is_valid() and profile_form.is_valid():
        if proForm.is_valid():
            product = proForm.save(commit=False)
            product.user = request.user
                #proForm.save()
            product.save()
            return redirect('home')
    else:
        proForm = ProductForm()
    return render(request,'home/home.html',{
        'pro': pro,
        'proForm': proForm
    })

'''

def add_product(request):
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)
            product.user = request.user   # ربط المنتج بصاحب الحساب
            product.save()
            return redirect("home")
    else:
        form = ProductForm()
    return render(request, "add.html", {"form": form})
'''
def edit_product(request, id):
    product = Product.objects.get(id=id)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect("home")

    form = ProductForm(instance=product)
    return render(request, "home/edit.html", {"form": form})


def delete_product(request, id):
    product = Product.objects.get(id=id)
    if request.method == "POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product.delete()
            return redirect("home")
    form = ProductForm(instance=product)
    return render(request,"home/delete.html",{'form':form})

templates/base_generic.html
{% load static %}
<html>
<head>

<!-- Mobile Specific Meta -->
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- Favicon-->
<link rel="shortcut icon" href="{% static 'img/gb1.jpg'%}>

<!-- Author Meta -->
<meta name="author" content="colorlib">

<!-- Meta Description -->
<meta name="description" content="">

<!-- Meta Keyword -->
<meta name="keywords" content="">

<!-- meta character set -->
<meta charset="UTF-8">

<!-- Site Title -->
<title>OBERA</title>
<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">

<!-- CSS ============================================= -->
<link rel="stylesheet" href="{% static 'css/linearicons.css'%}">
<link rel="stylesheet" href="{% static 'css/font-awesome.min.css'%}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css'%}">
<link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
<link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
<link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
<link rel="stylesheet" href="{% static 'css/owl.carousel.css'%}">
<link rel="stylesheet" href="{% static 'css/main.css'%}">

</head>

<body>

<header id="header" id="home">

<div class="header-top">
<div class="container">
<div class="row">
<div class="col-lg-6 col-sm-6 col-4 header-top-left no-padding">
<a href="tel:0926987111">0926987111</a>
<a href="mailto:elsharifmohamed369@gmail.com">elsharifmohamed369@gmail.com</a>
</div>
<div class="col-lg-6 col-sm-6 col-8 header-top-right no-padding">
 <ul>
  <li>
   <a href="#"><i class="fa fa-facebook"></i></a>
  </li>
  <li>
   <a href="#"><i class="fa fa-twitter"></i></a>
  </li>
  <li>
   <a href="#"><i class="fa fa-dribbble"></i></a>
  </li>
  <li>
   <a href="#"><i class="fa fa-behance"></i></a>
  </li>
 </ul>
</div>
</div>
</div>
</div>
<div class="container main-menu">
<div class="row align-items-center justify-content-between d-flex">
<div id="logo">
<a href="{% url 'home' %}">
<img src="{% static 'img/obera.png' %}" alt="" title="" />
</a>
</div>
<nav id="nav-menu-container">
 <ul class="nav-menu">
  <li class="menu-active">
   <a href="{% url 'home' %}">Home</a>
  </li>
<!--
  <li>
   <a href="#">About</a>
  </li>
  <li>
   <a href="#">Services</a>
  </li>
  <li>
   <a href="#">Projects</a>
  </li>

 
<li class="menu-has-children">
   <a href="">Pages</a>
   <ul>
    <li>
     <a href="#">Project Details</a>
    </li>
    <li>
     <a href="#">Elements</a>
    </li>
   </ul>
  </li>
  -->
  <li class="menu-has-children">
   <a href=" ">Register</a>
   <ul>
    <li>
     <a href="{% url 'accounts:signup' %}">SignUp</a>
    </li>
    <li>
     <a href="#">LogIn</a>
    </li>
   </ul>
  </li>
<!--  <li>
   <a href="#">Contact</a>
  </li>-->
 </ul>
</nav>
<!-- #nav-menu-container -->
</div>
</div>
</header>
<!-- #header -->

{% block content %}
{% endblock content %}

<script src="{% static 'js/vendor/jquery-2.2.4.min.js'%}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{% static 'js/vendor/bootstrap.min.js'%}"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{% static 'js/easing.min.js'%}"></script>
<script src="{% static 'js/hoverIntent.js'%}"></script>
<script src="{% static 'js/superfish.min.js'%}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js'%}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js'%}"></script>
<script src="{% static 'js/owl.carousel.min.js'%}"></script>
<script src="{% static 'js/jquery.nice-select.min.js'%}"></script>
<script src="{% static 'js/mail-script.js'%}"></script>
<script src="{% static 'js/main.js'%}"></script>
</body>
</html>

templates/home/delete.html
<html>
<head><title>حذف المنتج</title></head>
<body>

<h1>حذف المنتج: {{ product.title }}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> تأكيد الحذف</button>
</form>

<br>
<a href="{% url 'home' %}">رجوع للصفحة الرئيسية</a>

</body>
</html>

templates/home/edit.html
<html>
<head><title>تعديل المنتج</title></head>
<body>

<h1>تعديل المنتج: {{ product.title }}</h1>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">حفظ التعديلات</button>
</form>

<br>
<a href="{% url 'home' %}">رجوع للصفحة الرئيسية</a>

</body>
</html>

templates/home/home.html
{% load static %}
<html>
<head>
<title>
My Site
</title>
<link rel="manifest" href="{% static 'manifest.json' %}">
<script>
if ("serviceWorker" in navigator) {
  navigator.serviceWorker.register("{% static 'serviceworker.js' %}");
}
</script>
</head>
<body>
<nav id="nav-menu-container">
 <ul class="nav-menu">
  <li class="menu-active">
   <a href="{% url 'home' %}">الصفحه الرئيسيه</a>
  </li>
  
  <li>
   <a href="{% url 'accounts:profile' %}">صفحتك الشخصيه</a>
  </li>
  <li>
   <a href="{% url 'accounts:loggedOut' %}">
تسجيل الخروج</a>
  </li>
  <li>
   <a href="{% url 'accounts:signup' %}">الاشتراك بالموقع بحساب جديد</a>
  </li>
</nav>
</br>
<div>
<!-- بحث -->
<form method="get">
    <input type="text" name="q" placeholder="ابحث">
    </br>
    <button type="submit">بحث</button>
</form>

<br><br>
</div>
<div>
<form method='post'>
{% csrf_token %}
{{ proForm.as_p }}
<button type='submit'>أضافه</button>
</form>
</div>
</br>
<div>
{% for p in pro %}
<h1>{{ p.title }}</h1>
<h3>{{ p.price }}</h3>
{% if request.user == p.user %}
    <a href="{% url 'edit' p.id %}">تعديل</a>
    <a href="{% url 'delete' p.id %}">حذف</a>
<h6>____________</h6>
{% endif %}

<h6>____________</h6>
{% endfor %}
</div>
</body>
</html>

templates/home/index.html
<html>
<head>
<title>My Site</title>
</head>
<body>

<h1>اهلا بكم فى موقعى الرسمى</h1>

<!-- بحث -->
<form method="get">
    <input type="text" name="q" placeholder="ابحث باسم المنتج أو السعر" />
    <button type="submit">بحث</button>
</form>

<br><br>

<!-- إضافة منتج -->
<div>
<form method='post'>
{% csrf_token %}
{{ proForm.as_p }}
<button type='submit'>إضافة</button>
</form>
</div>

<br>

<!-- عرض المنتجات -->
<div>
{% for p in pro %}
<h1>{{ p.title }}</h1>
<h3>{{ p.price }}</h3>

<a href="/edit/{{ p.id }}/">تعديل</a> |
<a href="/delete/{{ p.id }}/" onclick="return confirm('هل تريد الحذف فعلاً؟');">حذف</a>

<h6>____________</h6>
{% endfor %}
</div>

</body>
</html>